server:
  port: ${PORT:8081}

spring:
  application:
    name: query-side-order
    exchange: order.events.fanout.exchange
    queue: order.view.event.stream   
  rabbitmq:
    host: my-rabbit
    username: test
    password: password
    
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.axonframework: DEBUG
    com.springaxon: DEBUG
    
info:
  app:
    name: Order service - Query Side
    description: Order service - Query Side (CQRS)
        
axon:
  eventhandling:
    processors:
      default:
        source: messageSourceOrder