version: "2"

services:
  my-rabbit:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_NODENAME: my-rabbit
      
  command-side-blog:
    image: springaxon/command-side-blog
    ports:
     - "8080:8080"
    entrypoint: ./wait-for-it.sh rabbitmq:5672 -t 60 --
    command: java -jar /app.jar
