version: "2"

services:

  my-mysql:
    image: mysql/mysql-server:5.6
    ports:
     - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blog
      - MYSQL_ROOT_HOST=%
      
  my-rabbit:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_NODENAME: my-rabbit
            
  command-side-blog:
    image: springaxon/command-side-blog
    ports:
     - "8080:8080"
    depends_on:
     - my-rabbit
         
  query-side-project:
    image: springaxon/query-side-blog
    ports:
     - "8083:8083"
    depends_on:
     - my-rabbit
