server:
  port: ${PORT:8080}

spring:
  application:
    name: command-side-order
  rabbitmq:
    host: my-rabbit
    username: test
    password: password
  datasource:
    url: jdbc:mysql://my-mysql:3306/order
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    validation-query: SELECT 1
  jpa:
        database: mysql
        show-sql: true
        hibernate:
            ddl-auto: create-drop
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.axonframework: DEBUG
    com.springaxon: DEBUG
    
info:
  app:
    name: Order service - Command Side
    description: Order service - Command Side (CQRS)
        
axon:
  amqp:
    exchange: order.events.fanout.exchange
    