server:
  port: ${PORT:8080}

spring:
  application:
    name: command-side-order
  rabbitmq:
    host: my-rabbit
    username: test
    password: password

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.axonframework: DEBUG
    com.springaxon: DEBUG
    
info:
  app:
    name: Order service - Command Side
    description: Blog service - Command Side (CQRS)
        
axon:
  amqp:
    exchange: order.events.fanout.exchange
    