server:
  port: 8080

spring:
  application:
    name: command-side-blog
  rabbitmq:
    host: my-rabbit
    username: test
    password: password

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.axonframework: DEBUG
    com.springaxon: DEBUG
    
info:
  app:
    name: Blog service - Command Side
    description: Blog service - Command Side (CQRS)
        
axon:
  amqp:
    exchange: blog.events.fanout.exchange
    